# Generated by Django 4.1.2 on 2023-05-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='parent',
            field=models.TextField(default=''),
        ),
    ]
